In [1]:
import numpy as np
import math
import string
from sympy import Matrix, pprint

In [23]:
alphabets = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',' ']
raw_text = input()
raw_text = raw_text.lower()
raw_text = "".join(c for c in raw_text if c in alphabets)
raw_text

the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to observe with experiments than those of other particles like neutrons and protons because electrons have a lower mass and hence a longer de broglie wavelength for a

'the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to observe with experiments than those of other particles like neutrons and protons because electrons have a lower mass and hence a longer de broglie wavelength for 

In [24]:
# of, to, in, it, is, be, as, at, so, we, he, by, or, on, do, if, me, my, up, an, go
first_most = ['t','h']
second_most = ['o','f']

def make_two_key(first_most,second_most):
    key = np.zeros(4).reshape(2,2)
    key[0][0] = ord(first_most[0]) - ord('a')
    key[0][1] = ord(first_most[1]) - ord('a')
    key[1][0] = ord(second_most[0]) - ord('a')
    key[1][1] = ord(second_most[1]) - ord('a')
    return key.astype(int)

def make_three_key(first_most,second_most,third_most):
    key = np.zeros(9).reshape(3,3)
    key[0][0] = ord(first_most[0]) - ord('a')
    key[0][1] = ord(first_most[1]) - ord('a')
    key[0][2] = ord(first_most[2]) - ord('a')
    key[1][0] = ord(second_most[0]) - ord('a')
    key[1][1] = ord(second_most[1]) - ord('a')
    key[1][2] = ord(second_most[2]) - ord('a')
    key[2][0] = ord(third_most[0]) - ord('a')
    key[2][1] = ord(third_most[1]) - ord('a')
    key[2][2] = ord(third_most[2]) - ord('a')
    return key.astype(int)

def most_common_digrams(cipher):
    mdict = {}
    input_text = list(cipher)
    input_text = list(filter((' ').__ne__, input_text))
    for i in range(0,len(input_text)-1,2):
        s = input_text[i] + input_text[i+1]
        if s not in mdict:
            mdict[s] = 1
        else:
            mdict[s] +=1
    sorted_x = sorted(mdict.items(), key=lambda kv: kv[1],reverse = True)
    a = sorted_x[0][0]
    b = sorted_x[1][0]
    print("most common digrams in the cipher text are ")
    print(a)
    print(b)
    return make_two_key(a,b)
    
def most_common_trigrams(cipher):
    mdict = {}
    input_text = list(cipher)
    input_text = list(filter((' ').__ne__, input_text))
    for i in range(0,len(input_text)-2,3):
        s = input_text[i] + input_text[i+1] + input_text[i+2] 
        if s not in mdict:
            mdict[s] = 1
        else:
            mdict[s] +=1
    sorted_x = sorted(mdict.items(), key=lambda kv: kv[1],reverse = True)
    a = sorted_x[0][0]
    b = sorted_x[1][0]
    c = sorted_x[2][0]
    print(a)
    print(b)
    print(c)
    return make_three_key(a,b,c)
    

In [25]:
most_common_digrams(raw_text)

most common digrams in the cipher text are 
el
th


array([[ 4, 11],
       [19,  7]])

In [15]:
# most_common_digrams(raw_cipher)

In [16]:
def prepare_text(raw_text,n=2):
    input_text = list(raw_text)
    input_text = list(filter((' ').__ne__, input_text))
    text = np.zeros(len(input_text))
    for a in range(len(input_text)):
        text[a] = ord(input_text[a]) - ord('a')
    l = len(input_text)
    if(l%n !=0 ):
        a = np.ones(n-l%n)*25
        text = np.append(text,a,axis = 0)
    text = text.reshape(int(text.shape[0]/n),n)
    return text.astype(int)

In [26]:
# key2 = most_common_digrams(raw_text)
raw_cipher = input()

xfw iutxcady jg g owwjsvcal ezyalzgm oscmpu  t  vu    lgyaw iutxcity eylchi gt gcufkfqa qml ryuexkcpel nizyoa ryqwbnjwj mryjwh mb gkj epmbu zxkjifkkaq tl dkj utxpjw sfphagut gtcacj nao bwv oamlkxpjn sorqidv sv ih ryuexkcpel sfphagutj mqwiqse xfey ylgf qt zmkyg zgqilmlfxw mm bbelqsnxcxwp ukj ryqwbnjw ylg g eeik xffk wy tmrdneeofkryn  syls vl dkj rdbgjw wenakfo yqwylyjssb hadedphgsw ml dkj ryqwbnjw huzghqk ky jfxitcrag naksivu rgqxkkfg iqbq tg t ylxzhuonoav thokw bsrdmosem xi dyjet la xfj itcektc ztnawa iycrcpfx  ihhur gjicajwt gb ggw ryqwbnjwm sna ciaimt xfm okug cyyfxis lqfki ga nyevuobgzy mzed vkj sffmg sslqlecjw rdhuqoztr yyck kpj ryuexkcpel sfphaguts eutxcadcr bswhufv badedphgsw mj zbgr xzyalzgmo nac dlwmo xfey ssg zdkgraz omxf bgkjd jzyalzgmo nau nna ih mxvxkxxctc gryk grxsh zkj qqgf rdpijialmo la ryqwbnjwg gwv kkecji sv zcsevty mzek jfljieoxket xfna xfyaa qw zxfji sfphagutn uycx ksabnjwg gjf rdbgjwj mqwiqse ryqwbnjwb wlwk k ybcou rceg gjf kjgzk k ybsxji az vhoggry mlwryxkhmn pvu s

In [18]:
def IC(text):
    mdict = {}
    l = 0
    for a in text:
        l+=1
        if a not in mdict:
            mdict[a] = 1
        else:
            mdict[a] +=1
    s = 0
    for a in mdict:
        s += mdict[a]*(mdict[a]-1)
    return (1.0*s)/(1.0*l*(l-1))

In [19]:
# Most common bigrams (in order)
# th, he, in, en, nt, re, er, an, ti, es, on, at, se, nd, or, ar, al, te, co, de, to, ra, et, ed, it, sa, em, ro.
# Most common trigrams (in order)
# the, and, tha, ent, ing, ion, tio, for, nde, has, nce, edt, tis, oft, sth, men

# decrypt function for keysize = 2, argument "raw_cipher" is the cipher text.
def decrypt_2(raw_cipher,n=2):       
    a = "el"  # assumed most common di-gram 
    b = "th"  # assumed most common di-gram 
    C = most_common_digrams(raw_cipher).T    # make the matrix C
    P = make_two_key(a,b).T                  # make the matrix P from a,b
    
    # prepare_text func. makes set of two from the cipher text
    # for decrypting using the obtained key.
    cipher = prepare_text(raw_cipher,2)    
    
    #following code computes the key, K using P and C
    temp = Matrix(P)
    Pinv = temp.inv_mod(26)    # P_inverse
    key = np.mod(np.dot(C,Pinv),26).astype(int)  #finding the key, using K = C × P_inverse 
    print("encryption key is : ")
    print(key)
    tempkey = Matrix(key)
    kinv = tempkey.inv_mod(26)
    
    # finding the decrypted text using the obtained key, K_inverse
    # for every block of the text of size 2
    dec = []
    dec_text = ""
    for a in range(len(cipher)):
        b = np.dot(kinv,cipher[a])
        for i in range(len(b)):
            dec += [b[i]%26]
            
    # the following block of code is to put spaces at corresponding places.
    ind = 0
    for i in range(len(raw_cipher)):
        if(raw_cipher[i]!=' '):
            dec_text += chr(ord('a') + int(dec[ind])) 
            ind +=1
        else:
            dec_text += ' '
            
    print("IC of the decrypted text is : ",IC(dec_text))
    return dec_text



def decrypt_3(raw_cipher,n=3):
    x = "the"
    y = "and"
    z = "tha"
    C = most_common_trigrams(raw_cipher).T
    P = make_three_key(x,y,z).T
    cipher = prepare_text(raw_cipher,3)
    temp = Matrix(P)
    Pinv = temp.inv_mod(26)
    key = np.mod(np.dot(C,Pinv),26).astype(int)
    tempkey = Matrix(key)
    print("encryption key is : ")
    print(key)
    kinv = tempkey.inv_mod(26)
    dec = []
    dec_text = ""
    for a in range(len(cipher)):
        b = np.dot(kinv,cipher[a])
        for i in range(len(b)):
            dec += [b[i]%26]
#     print(dec)
    ind = 0
    for i in range(len(raw_cipher)):
        if(raw_cipher[i]!=' '):
            dec_text += chr(ord('a') + int(dec[ind])) 
            ind +=1
        else:
            dec_text += ' '
    print("IC of the decrypted text is : ",IC(dec_text))
    return dec_text



In [27]:
original_text = decrypt_2(raw_cipher,2)
print()
print("original text is: ")
print(original_text)

most common digrams in the cipher text are 
ry
xf
encryption key is : 
[[22  3]
 [ 9  6]]
IC of the decrypted text is :  0.07404781703985008

original text is: 
the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to ob

In [92]:
def IC(text):
    mdict = {}
    l = 0
    for a in text:
        l+=1
        if a not in mdict:
            mdict[a] = 1
        else:
            mdict[a] +=1
    s = 0
    for a in mdict:
        s += mdict[a]*(mdict[a]-1)
    return (1.0*s)/(1.0*l*(l-1))
            

In [22]:
IC(original_text)

0.07404781703985008

In [21]:
original_text

'the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to observe with experiments than those of other particles like neutrons and protons because electrons have a lower mass and hence a longer de broglie wavelength for 

In [88]:
# p = make_two_key("re","in")
# c = make_two_key("wv","hu")
p = np.array([17,4,8,13]).reshape(2,2).T
c = np.array([22,21,7,20]).reshape(2,2).T

pprint(p)
temp = Matrix(p)
Pinv = temp.inv_mod(26)
pprint(Pinv)
np.mod(np.dot(c,Pinv),26)

 [[17  8]
 [ 4 13]]
⎡13  10⎤
⎢      ⎥
⎣18  21⎦


array([[22, 3],
       [9, 6]], dtype=object)

array([[1, 0],
       [0, 1]], dtype=object)

In [85]:
# a  = np.array([22,3,9,6]).reshape(2,2)
a  = np.array([2,5,5,0]).reshape(2,2)

# temp = Matrix(a)
# k = temp.inv_mod(26)
pprint(a)
b = np.array([ord('r')-ord('a'),ord('e')-ord('a')]).astype(int)
c = np.mod(np.dot(a,b),26)
print(chr(c[0]+ord('a')))
print(chr(c[1]+ord('a')))

 [[2 5]
 [5 0]]
c
h
