In [1]:
import numpy as np
import math
import string
from sympy import Matrix, pprint

In [2]:
key = input()
key = list(map(int,key.split(' ')))

22 3 9 6


In [3]:
n = math.sqrt(len(key))
n = int(n)
key = np.array(key).reshape(n,n)
key

array([[22,  3],
       [ 9,  6]])

In [15]:
raw_text = input()

the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to observe with experiments than those of other particles like neutrons and protons because electrons have a lower mass and hence a longer de broglie wavelength for a

In [16]:
def prepare_text(raw_text):
    input_text = list(raw_text)
    input_text = list(filter((' ').__ne__, input_text))
    text = np.zeros(len(input_text))
    for a in range(len(input_text)):
        text[a] = ord(input_text[a]) - ord('a')
    print(text)
    l = len(input_text)
    print(l)
    if(l%n !=0 ):
        a = np.ones(n-l%n)*25
        print(a)
        text = np.append(text,a,axis = 0)
    text = text.reshape(int(text.shape[0]/n),n)
    return text

In [17]:
def encrypt(raw_text):
    text = prepare_text(raw_text)
    enc = []
    enc_text = ""
    for a in range(len(text)):
        b = np.dot(key,text[a])
        for i in range(len(b)):
            enc += [b[i]%26]
    print(enc)
    ind = 0
    for i in range(len(raw_text)):
        if(raw_text[i]!=' '):
            enc_text += chr(ord('a') + int(enc[ind])) 
            ind +=1
        else:
            enc_text += ' '
    return enc_text



In [18]:
encrypt(raw_text)

[19.  7.  4. ... 14. 13. 18.]
2860
[23.0, 5.0, 22.0, 8.0, 20.0, 19.0, 23.0, 2.0, 0.0, 3.0, 24.0, 9.0, 6.0, 6.0, 14.0, 22.0, 22.0, 9.0, 18.0, 21.0, 2.0, 0.0, 11.0, 4.0, 25.0, 24.0, 0.0, 11.0, 25.0, 6.0, 12.0, 14.0, 18.0, 2.0, 12.0, 15.0, 20.0, 19.0, 21.0, 20.0, 11.0, 6.0, 24.0, 0.0, 22.0, 8.0, 20.0, 19.0, 23.0, 2.0, 8.0, 19.0, 24.0, 4.0, 24.0, 11.0, 2.0, 7.0, 8.0, 6.0, 19.0, 6.0, 2.0, 20.0, 5.0, 10.0, 5.0, 16.0, 0.0, 16.0, 12.0, 11.0, 17.0, 24.0, 20.0, 4.0, 23.0, 10.0, 2.0, 15.0, 4.0, 11.0, 13.0, 8.0, 25.0, 24.0, 14.0, 0.0, 17.0, 24.0, 16.0, 22.0, 1.0, 13.0, 9.0, 22.0, 9.0, 12.0, 17.0, 24.0, 9.0, 22.0, 7.0, 12.0, 1.0, 6.0, 10.0, 9.0, 4.0, 15.0, 12.0, 1.0, 20.0, 25.0, 23.0, 10.0, 9.0, 8.0, 5.0, 10.0, 10.0, 0.0, 16.0, 19.0, 11.0, 3.0, 10.0, 9.0, 20.0, 19.0, 23.0, 15.0, 9.0, 22.0, 18.0, 5.0, 15.0, 7.0, 0.0, 6.0, 20.0, 19.0, 6.0, 19.0, 2.0, 0.0, 2.0, 9.0, 13.0, 0.0, 14.0, 1.0, 22.0, 21.0, 14.0, 0.0, 12.0, 11.0, 10.0, 23.0, 15.0, 9.0, 13.0, 18.0, 14.0, 17.0, 16.0, 8.0, 3.0, 21.0, 18.0, 21.0,

'xfw iutxcady jg g owwjsvcal ezyalzgm oscmpu  t  vu    lgyaw iutxcity eylchi gt gcufkfqa qml ryuexkcpel nizyoa ryqwbnjwj mryjwh mb gkj epmbu zxkjifkkaq tl dkj utxpjw sfphagut gtcacj nao bwv oamlkxpjn sorqidv sv ih ryuexkcpel sfphagutj mqwiqse xfey ylgf qt zmkyg zgqilmlfxw mm bbelqsnxcxwp ukj ryqwbnjw ylg g eeik xffk wy tmrdneeofkryn  syls vl dkj rdbgjw wenakfo yqwylyjssb hadedphgsw ml dkj ryqwbnjw huzghqk ky jfxitcrag naksivu rgqxkkfg iqbq tg t ylxzhuonoav thokw bsrdmosem xi dyjet la xfj itcektc ztnawa iycrcpfx  ihhur gjicajwt gb ggw ryqwbnjwm sna ciaimt xfm okug cyyfxis lqfki ga nyevuobgzy mzed vkj sffmg sslqlecjw rdhuqoztr yyck kpj ryuexkcpel sfphaguts eutxcadcr bswhufv badedphgsw mj zbgr xzyalzgmo nac dlwmo xfey ssg zdkgraz omxf bgkjd jzyalzgmo nau nna ih mxvxkxxctc gryk grxsh zkj qqgf rdpijialmo la ryqwbnjwg gwv kkecji sv zcsevty mzek jfljieoxket xfna xfyaa qw zxfji sfphagutn uycx ksabnjwg gjf rdbgjwj mqwiqse ryqwbnjwb wlwk k ybcou rceg gjf kjgzk k ybsxji az vhoggry mlwryxkhmn pvu 

In [19]:
raw_cipher = input()

xfw iutxcady jg g owwjsvcal ezyalzgm oscmpu  t  vu    lgyaw iutxcity eylchi gt gcufkfqa qml ryuexkcpel nizyoa ryqwbnjwj mryjwh mb gkj epmbu zxkjifkkaq tl dkj utxpjw sfphagut gtcacj nao bwv oamlkxpjn sorqidv sv ih ryuexkcpel sfphagutj mqwiqse xfey ylgf qt zmkyg zgqilmlfxw mm bbelqsnxcxwp ukj ryqwbnjw ylg g eeik xffk wy tmrdneeofkryn  syls vl dkj rdbgjw wenakfo yqwylyjssb hadedphgsw ml dkj ryqwbnjw huzghqk ky jfxitcrag naksivu rgqxkkfg iqbq tg t ylxzhuonoav thokw bsrdmosem xi dyjet la xfj itcektc ztnawa iycrcpfx  ihhur gjicajwt gb ggw ryqwbnjwm sna ciaimt xfm okug cyyfxis lqfki ga nyevuobgzy mzed vkj sffmg sslqlecjw rdhuqoztr yyck kpj ryuexkcpel sfphaguts eutxcadcr bswhufv badedphgsw mj zbgr xzyalzgmo nac dlwmo xfey ssg zdkgraz omxf bgkjd jzyalzgmo nau nna ih mxvxkxxctc gryk grxsh zkj qqgf rdpijialmo la ryqwbnjwg gwv kkecji sv zcsevty mzek jfljieoxket xfna xfyaa qw zxfji sfphagutn uycx ksabnjwg gjf rdbgjwj mqwiqse ryqwbnjwb wlwk k ybcou rceg gjf kjgzk k ybsxji az vhoggry mlwryxkhmn pvu s

In [20]:
def decrypt(raw_cipher):
    cipher = prepare_text(raw_cipher)
    tempkey = Matrix(key)
    kinv = tempkey.inv_mod(26)
    dec = []
    dec_text = ""
    for a in range(len(cipher)):
        b = np.dot(kinv,cipher[a])
        for i in range(len(b)):
            dec += [b[i]%26]
    print(dec)
    ind = 0
    for i in range(len(raw_cipher)):
        if(raw_cipher[i]!=' '):
            dec_text += chr(ord('a') + int(dec[ind])) 
            ind +=1
        else:
            dec_text += ' '
    return dec_text
    

In [21]:
decrypt(raw_cipher)

[23.  5. 22. ... 21.  2. 17.]
2860
[19.0000000000000, 7.00000000000000, 4.00000000000000, 4.00000000000000, 11.0000000000000, 4.00000000000000, 2.00000000000000, 19.0000000000000, 17.0000000000000, 14.0000000000000, 13.0000000000000, 8.00000000000000, 18.0000000000000, 0, 18.0000000000000, 20.0000000000000, 1.00000000000000, 0, 19.0000000000000, 14.0000000000000, 12.0000000000000, 8.00000000000000, 2.00000000000000, 15.0000000000000, 0, 17.0000000000000, 19.0000000000000, 8.00000000000000, 2.00000000000000, 11.0000000000000, 4.00000000000000, 18.0000000000000, 24.0000000000000, 12.0000000000000, 1.00000000000000, 14.0000000000000, 11.0000000000000, 4.00000000000000, 14.0000000000000, 17.0000000000000, 22.0000000000000, 7.00000000000000, 14.0000000000000, 18.0000000000000, 4.00000000000000, 4.00000000000000, 11.0000000000000, 4.00000000000000, 2.00000000000000, 19.0000000000000, 17.0000000000000, 8.00000000000000, 2.00000000000000, 2.00000000000000, 7.00000000000000, 0, 17.0000000000000

'the electron is a subatomic particle symbol  e  or    whose electric charge is negative one elementary charge electrons belong to the first generation of the lepton particle family and are generally thought to be elementary particles because they have no known components or substructure the electron has a mass that is approximately  that of the proton quantum mechanical properties of the electron include an intrinsic angular momentum spin of a halfinteger value expressed in units of the reduced planck constant  being fermions no two electrons can occupy the same quantum state in accordance with the pauli exclusion principle like all elementary particles electrons exhibit properties of both particles and waves they can collide with other particles and can be diffracted like light the wave properties of electrons are easier to observe with experiments than those of other particles like neutrons and protons because electrons have a lower mass and hence a longer de broglie wavelength for 